//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.event.*;



public class dockingScreen extends JFrame {
    private JButton jcomp1;
    private JTextArea jcomp2;
    private JList jcomp3;

    public dockingScreen() {
   
    	
        //construct preComponents
        String[] jcomp3Items = {"Sim 1", "Sim 2", "Sim 3"};

        JButton jcomp1 = new JButton(new ImageIcon("Button.jpg"));
        jcomp2 = new JTextArea (5, 5);
        jcomp3 = new JList (jcomp3Items);
        JButton jcomp4 = new JButton(new ImageIcon("Button0.jpg"));

        //adjust size and set layout
        setPreferredSize (new Dimension (330, 475));
        setLayout (null);

        //add components
        add (jcomp1);
        add (jcomp2);
        add (jcomp3);
        add (jcomp4);

        //set component bounds (only needed by Absolute Positioning)
        jcomp1.setBounds (109, 330, 110, 60);
        jcomp2.setBounds (340, 225, 145, 20);
        jcomp3.setBounds (110, 170, 105, 130);
        jcomp4.setBounds (109, 405, 110, 60);
        
        JLabel background;
    	ImageIcon img = new ImageIcon("Background.jpg");
    	background = new JLabel("", img, JLabel.CENTER);
    	background.setBounds(0,0,330,475);
    	add(background);
    	setVisible(true);
    	
    	jcomp1.addActionListener(new ActionListener()
    	{
    	  public void actionPerformed(ActionEvent e)
    	  {
    	    // display/center the jdialog when the button is pressed
    	    mainFrame.init();
    	    dispose();
    	    
    	  }
    	});
//    	Icon i=new ImageIcon("Button.jpg");
//    	
//    	jcomp1.setIcon(i);
    }


    public static void main (String[] args) {
    	
        JFrame frame = new JFrame ("Sim Capital");
        frame.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
        frame.getContentPane().add(new dockingScreen());
        frame.pack();
        frame.setVisible (true);
    }
}
