//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.event.*;

public class mainFrame extends JPanel {
    private JTextArea jcomp1;
    private JTextArea jcomp2;

    public mainFrame() {
        //construct components
        jcomp1 = new JTextArea (5, 5);
        jcomp2 = new JTextArea (5, 5);

        //adjust size and set layout
        setPreferredSize (new Dimension (944, 574));
        setLayout (null);

        //add components
        add (jcomp1);
        add (jcomp2);

        //set component bounds (only needed by Absolute Positioning)
        jcomp1.setBounds (340, 255, 135, 25);
        jcomp2.setBounds (340, 330, 140, 25);
    }


    public static void init() {
        JFrame frame = new JFrame ("mainFrame");
        frame.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
        frame.getContentPane().add (new mainFrame());
        frame.pack();
        frame.setVisible (true);
    }
}
